// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6.Models;

#nullable disable

namespace Mission6.Migrations
{
    [DbContext(typeof(ContextClass))]
    [Migration("20230222000819_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Mission6.Models.MovieForm", b =>
                {
                    b.Property<int>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            AppId = 1,
                            Category = "Musical",
                            Director = "Richard Linklatler",
                            Edited = true,
                            LentTo = "Josh",
                            Notes = "Great Movie",
                            Rating = "PG-13",
                            Title = "School of Rock",
                            Year = 2003
                        },
                        new
                        {
                            AppId = 2,
                            Category = "Fantasy",
                            Director = "Peter Jackson",
                            Edited = true,
                            LentTo = "Josh",
                            Notes = "Fantastic Movie",
                            Rating = "PG-13",
                            Title = "Lord of the Rings",
                            Year = 2001
                        },
                        new
                        {
                            AppId = 3,
                            Category = "Drama",
                            Director = "Damien Chazelle",
                            Edited = true,
                            LentTo = "Josh",
                            Notes = "Amazing Film",
                            Rating = "R",
                            Title = "Whiplash",
                            Year = 2014
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
